name: Building project

on:
  push:
    branches: 
      - master

jobs:
  first-basic-build:
    strategy:
      matrix:
        node-versions: [8.x, 10.x, 12.x]
    runs-on: [ubuntu-latest]
    name: Node build
    steps:
      - name: first step for the first build
        env:
          VAR1: variable 1
          VAR2: variable 2
        run:
          echo step 1 $VAR1 $VAR2 ${{ matrix.node-version }}
      - name: second step for the first build
        env:
          VAR3: variable 3
          VAR4: variable 4
        run:
          echo $VAR3 $VAR4 $VAR1 $VAR2 
                    
  Second-basic-build:
    runs-on: [ubuntu-latest]
    needs: [first-basic-build]
    name: Second Build
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        working-directory: ./web-app/client/
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true 
      - name: first step for the second build
        env:
          VAR1: variable 12
          VAR2: variable 22
        run:
          echo second ${{ matrix.node-version }} $VAR1 $VAR2
      - name: second step for the second build
        env:
          VAR3: variable 32
          VAR4: variable 4
        if: success()
        run:
          echo success $VAR3 $VAR4 $VAR1 $VAR2
   
